# Generated by Django 2.1.3 on 2018-12-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(default='root', max_length=64)),
                ('password', models.CharField(default='', max_length=128)),
                ('private_key', models.TextField(blank=True, max_length=4096, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '管理用户',
                'verbose_name_plural': '管理用户',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16, null=True, verbose_name='登录用户')),
                ('host', models.CharField(max_length=128, null=True, verbose_name='登录主机')),
                ('remote_ip', models.CharField(max_length=16, verbose_name='来源IP')),
                ('login_type', models.CharField(choices=[('web', 'web'), ('ssh', 'ssh')], default='web', max_length=8, verbose_name='登录方式')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('record_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='对象存储Name')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecorderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Log')),
            ],
            options={
                'verbose_name': '回放日志',
                'verbose_name_plural': '回放日志',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('idc', models.CharField(choices=[('qcloud', '腾讯云'), ('aliyun', '阿里云'), ('aws', 'AWS'), ('other', '其他')], default='other', max_length=16, verbose_name='云厂商')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('os_platform', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Other', 'Other')], default='Linux', max_length=32, verbose_name='系统类型')),
                ('os_distribution', models.CharField(blank=True, max_length=32, null=True, verbose_name='OS厂商')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN编号')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('public_key', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.AdminUser')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServerAuthRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('user', models.CharField(max_length=256)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('server', models.ManyToManyField(blank=True, null=True, to='assets.Server')),
            ],
            options={
                'verbose_name': '资产授权规则',
                'verbose_name_plural': '资产授权规则',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': '服务器组',
                'verbose_name_plural': '服务器组',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Tag标签',
                'verbose_name_plural': 'Tag标签',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TtyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='命令执行时间')),
                ('cmd', models.CharField(max_length=200)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Log')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
        migrations.AddField(
            model_name='serverauthrule',
            name='servergroup',
            field=models.ManyToManyField(blank=True, null=True, to='assets.ServerGroup'),
        ),
        migrations.AddField(
            model_name='server',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='assets.ServerGroup'),
        ),
        migrations.AddField(
            model_name='server',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='assets.Tag'),
        ),
    ]
