# Generated by Django 2.1.3 on 2018-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128, unique=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('idc', models.CharField(choices=[('qcloud', '腾讯云'), ('aliyun', '阿里云'), ('aws', 'AWS'), ('other', '其他')], default='other', max_length=16, verbose_name='云厂商')),
                ('db_type', models.CharField(choices=[('MySQL', 'MySQL'), ('MariaDB', 'MariaDB'), ('MongoDB', 'MongoDB'), ('Redis', 'Redis'), ('Memcache', 'Memcache'), ('Other', 'Other')], default='MySQL', max_length=32, verbose_name='数据库类型')),
                ('db_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='数据库版本')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('group', models.ManyToManyField(blank=True, null=True, to='assets.ServerGroup')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='assets.Tag')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
                'ordering': ['-id'],
            },
        ),
    ]
