# Generated by Django 2.1.3 on 2018-11-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(default='root', max_length=64)),
                ('password', models.CharField(default='', max_length=128)),
                ('private_key', models.TextField(blank=True, max_length=4096, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '管理用户',
                'verbose_name_plural': '管理用户',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('idc', models.CharField(choices=[('qcloud', '腾讯云'), ('aliyun', '阿里云'), ('aws', 'AWS'), ('other', '其他')], default='other', max_length=16, verbose_name='云厂商')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('os_platform', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], default='Linux', max_length=32, verbose_name='系统类型')),
                ('os_distribution', models.CharField(blank=True, max_length=32, null=True, verbose_name='OS厂商')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN编号')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.AdminUser')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': '服务器组',
                'verbose_name_plural': '服务器组',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='server',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='assets.ServerGroup'),
        ),
    ]
