# Generated by Django 2.1.3 on 2018-12-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181120_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16, null=True, verbose_name='登录用户')),
                ('host', models.CharField(max_length=16, null=True, verbose_name='登录主机')),
                ('remote_ip', models.CharField(max_length=16, verbose_name='来源IP')),
                ('login_type', models.CharField(choices=[('web', 'web'), ('ssh', 'ssh')], default='web', max_length=8, verbose_name='登录方式')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='TtyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='命令执行时间')),
                ('cmd', models.CharField(max_length=200)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Log')),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='os_platform',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Other', 'Other')], default='Linux', max_length=32, verbose_name='系统类型'),
        ),
    ]
