# Generated by Django 2.1.3 on 2019-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_dbserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='role',
            field=models.CharField(choices=[('master', 'master'), ('slave', 'slave'), ('bak', 'bak')], default='master', max_length=16, verbose_name='角色'),
        ),
    ]
