# Generated by Django 2.1.3 on 2019-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_dbserver_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='role',
            field=models.CharField(choices=[('master', '主'), ('slave', '从'), ('backup', '备')], default='master', max_length=16, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.CharField(choices=[('qcloud', '腾讯云'), ('aliyun', '阿里云'), ('aws', 'AWS'), ('internal', '内网'), ('other', '其他')], default='other', max_length=16, verbose_name='云厂商'),
        ),
    ]
