# Generated by Django 2.1.3 on 2019-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_dbserver_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('id_rsa', models.TextField(blank=True, max_length=4096, null=True)),
                ('id_rsa_pub', models.TextField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'verbose_name': 'CMDB配置表',
                'verbose_name_plural': 'CMDB配置表',
            },
        ),
    ]
