# Generated by Django 2.1.3 on 2018-12-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181206_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '回放日志',
                'verbose_name_plural': '回放日志',
            },
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-id'], 'verbose_name': '管理用户', 'verbose_name_plural': '管理用户'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id'], 'verbose_name': '登录日志', 'verbose_name_plural': '登录日志'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-id'], 'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
        migrations.AlterModelOptions(
            name='servergroup',
            options={'ordering': ['-id'], 'verbose_name': '服务器组', 'verbose_name_plural': '服务器组'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'Tag标签', 'verbose_name_plural': 'Tag标签'},
        ),
        migrations.AddField(
            model_name='recorderlog',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Log'),
        ),
    ]
