# Generated by Django 2.1.3 on 2018-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20181207_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
    ]
