# Generated by Django 2.1.3 on 2018-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20181207_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='public_key',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
